# For setting up kind cluster with local environment
# Be sure to confirm already installed docker in the laptop
---
apiVersion: kind.sigs.k8s.io/v1alpha3
kind: Cluster
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
